### ISSUE TITLE
[FEATURE REQ] Insert hyperlinks in source text of notes

### ISSUE THREAD

**Issue by Jefferderp** [take6/obsidian-plugin-auto-hyperlink#3]
Hello!

Instead of only creating hyperlinks in reading mode, I would love it if there were a setting to permanently insert hyperlinks in the source text of my notes.

I currently find myself switching between editing/reading mode to access any automatic hyperlinks.

Thanks for this great plugin.

**Comment by take6** [comment]
Thank you very much @Jefferderp for your request. Requested feature is definitely a good one, and I actually hoping to realize it as well. But I'm kind of newbie for Javascript/Typescript. I might not have sufficient skill, but I will try!

**Comment by Jefferderp** [comment]
Not to worry. I greatly appreciate your plugin as-is, it makes me more productive every day!

**Comment by mattkenn4545** [comment]
Getting this functional in live-preview would be game changing for me.  I want to mention things like Jira links etc.. directly in my notes by their ID and don't actually want the markdown to have links etc... 

This plugin works perfectly but I essentially never use reading mode.

**Comment by take6** [comment]
I learned that there is a development guide that enables to do something in editor view.

https://docs.obsidian.md/Plugins/Editor/Editor
https://docs.obsidian.md/Plugins/Editor/Editor+extensions

It seems it's possible to insert link into editor view in real time. I will try!

**Comment by take6** [comment]
@Jefferderp, @mattkenn4545, I've released 0.4.1. This version includes **experimental** feature to insert hyperlink in-place. To enable the feature, you need to explicitly turn on in plugin setting (there is a toggle for the feature). The link is inserted when you typed any string that doesn't match the pattern (or return key). For example, if you configured the plugin to match the string "Obsidian", link is not yet inserted when you completed to type "Obsidian". Instead, the link will be inserted after you type any character, "Obsidian " (whitespace), for example, or return key. Then, "Obsidian " is replaced with "[Obsidian](https://github.com/obsidianmd) ". The feature is still unstable. I will be testing by myself in the next few days. But please test it if you are interested in.

**Comment by Jefferderp** [comment]
This works great, thank you!

I'm noticing that sometimes the cursor is jumping to the start of the line after a hyperlink is inserted.

Also, it would be beneficial if the list of "trigger" characters (currently space and enter) be expanded to include these `,.!":;`, which will cover more edge cases. Ideally, the user could specify a list of characters in settings.

**Comment by take6** [comment]
Hi @Jefferderp,

Thank you for the trial. 

> I'm noticing that sometimes the cursor is jumping to the start of the line after a hyperlink is inserted.

Thanks. I will take a look.

> Also, it would be beneficial if the list of "trigger" characters (currently space and enter) be expanded to include these ,.!":;, which will cover more edge cases. Ideally, the user could specify a list of characters in settings.

Any character that terminates pattern match will trigger the insertion of the link. In the above example, "Obsidian " and "Obsidian," should have the same effect. Please try any character, and let me know if you have any problem.

**Comment by Jefferderp** [comment]
> Any character that terminates pattern match will trigger the insertion of the link. In the above example, "Obsidian " and "Obsidian," should have the same effect. Please try any character, and let me know if you have any problem.

I was going through some old notes which already contained a matching string, typically followed by a comma, and observed this behavior then. This makes sense though, as this text was immediately followed by non-matching characters. I had to manually trigger a match by adding and removing a space. **This was also when the cursor would jump to the start of the line** (sometimes).

I can confirm that there's no matching issue, it was just my edge use case.

Thanks!

**Comment by take6** [comment]
Thanks @Jefferderp for your feedback! I created #5 for the cursor issue. I will take a look.

**Comment by take6** [comment]
@Jefferderp, I think I've fixed cursor issue.

**Comment by Jefferderp** [comment]
Thanks for the fix! I'm experiencing a new bug now, where the last character of a pattern match is being duplicated. Please see the attached video.

https://github.com/take6/obsidian-plugin-auto-hyperlink/assets/13530594/947340ab-62de-4f1b-8913-f1c875800ca3

**Comment by take6** [comment]
Thank you @Jefferderp for the bug report! I will open another issue and work on it as soon as possible.

**Comment by take6** [comment]
created #8.
