### ISSUE TITLE
the last character of a pattern match is being duplicated

### ISSUE THREAD

**Issue by take6** [take6/obsidian-plugin-auto-hyperlink#8]
Reported by @Jefferderp. 

https://github.com/take6/obsidian-plugin-auto-hyperlink/assets/13530594/947340ab-62de-4f1b-8913-f1c875800ca3

**Comment by Jefferderp** [comment]
Hello! Thanks for opening this on my behalf. I haven't experienced a repeat of this bug. Please feel free to close this issue, and I'll update if the bug returns.

**Comment by take6** [comment]
Hi @Jefferderp, 

Thank you very much for sharing the update on your side. Great to hear that. Then, I will close this issue in the meantime. Please let me know if you encounter the same problem. Thanks!

**Comment by take6** [comment]
Closing the issue as the issue is not reproduced. Will re-open if it happens again.
