### ISSUE TITLE
It should be possible to create links from a token with an indetermined number of digits

### ISSUE THREAD

**Issue by JasonWThompson** [take6/obsidian-plugin-auto-hyperlink#9]
In terms of [XY problem](https://en.wikipedia.org/wiki/XY_problem), my Y problem is that I'd like some way to use this plugin in editor mode, andallow for a variable length of numbers in my token that should be expanded. My X problem (described below) is that I can't use a lookahead regex to resolve this issue. But I'd be happy with a different method to achieve the goal of using variable length of numbers in editor mode.

I have the following configuration in order to match my Jira tickets:

```javascript
{
    "MYPROJECT-\\d+":"https://jira.example.com/browse/$0"
}
```

This works fine except that if I'm trying to type `MYPROJECT-1234`, this will transform the link after getting to `MYPROJECT-1`. So, I thought I'd tell it to use a lookahead. I transformed my config to look like this:

```javascript
{
    "MYPROJECT-\\d+(?=\\s)":"https://jira.example.com/browse/$0"
}
```

This didn't seem to work.

Today, I'm just using fixed number lengths as a workaround. But given the newness of MYPROJECT, I anticipate that we'll break into 3 digits soon and then 4 after that.

**Comment by JasonWThompson** [comment]
I noticed something else while using this. Let's say my config looks like this:

```javascript
{
    "MYPROJECT-\\d{3}":"https://jira.example.com/browse/$0"
}
```

If I type in `MYPROJECT-123`, it does not add the hyperlink. It's only after I type in the next character that the hyperlink is applied. So it seems like the logic is that it doesn't apply the link until the next character is typed _after_ the record that matches. So perhaps if the next character creates a record that matches, it should also wait until the user types in a character that doesn't match. So going back to this config:

```javascript
{
    "MYPROJECT-\\d+":"https://jira.example.com/browse/$0"
}
```

If I type in `MYPROJECT-1`, it should not replace it. But today when I type in `MYPROJECT-12`, it will replace `MYPROJECT-1` with the link. Perhaps if the logic was changed to say something like, "The new character also matches the pattern, so I should continue to hold off turning it into a link" then it would solve my Y problem above. Maybe if I have some time after work, I'll take a look at the source and see if I can throw together a PR that will implement this idea.

**Comment by take6** [comment]
Hi @JasonWThompson, 

Thank you for using my plugin! Actually my motivation of developing this plugin was to insert a link to JIRA ticket automatically. I tested your setting in my environment (MacBook Air, Sonoma 14.5) and it worked fine. FYI, the plugin works as follows:

1. wait for a string that matches a pattern
2. when matched string was found, watch the string until the user types any character that break the match
3. when the match was broken, insert a hyperlink

For example, the plugin starts watching the match when you type `MYPROJECT-1`. After that, it keeps watching your inputs. As long as you type any digits, link will not be inserted, e.g., you will not see the link if your input is `MYPROJECT-111111`. Finally, when you type non-digit character, e.g. whitespace, link is inserted. At this moment, `MYPROJECT-111111 ` will turn into `[MYPROJECT-111111](https://jira.example.com/browse/MYPROJECT-111111) ` and it is rendered as "[MYPROJECT-111111](https://jira.example.com/browse/MYPROJECT-111111) ".

It seems to me that the problem what you describe is `MYPROJECT-11` turned into `[MYPROJECT-1](https://jira.example.com/browse/MYPROJECT-1)1` so you saw "[MYPROJECT-1](https://jira.example.com/browse/MYPROJECT-1)1". Is my understanding correct?

**Comment by JasonWThompson** [comment]
Your assessment is correct, @take6. That being said, I just tried it out again this morning and it worked the way I wanted it to. 😅 I don't know why it was behaving differently yesterday since I didn't update it today. Since I can't reproduce this behavior anymore, I'll close it.

**Comment by take6** [comment]
Hi, @JasonWThompson. OK. Good to hear that the plugin worked as expected!
